description: Job for CMU robust verification code

auth:
  # which virtual cluster you belong to (msrlabs, etc.). Everyone has access to "pnrsy".
  vc: msrlabs
  # physical cluster to use (cam, gcr, rr1, rr2) or Azure clusters (eu1, eu2, etc.)
  cluster: gcr
  docker:
    image: hadisalman/test:latest

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  code_upload: true
  local_dir: $CONFIG_DIR

data:
#   data upload is not required for this example
  data_upload: false
  local_dir: $CONFIG_DIR/data
  remote_dir: data

# list of jobs to run, we run 2 jobs in this example
jobs:
  # name must be unique across the jobs
- name: job_large_cifar_parallel
  # one gpu
  sku: G1
  command:
  - pip install --user tensorflow tensorboard
  - pip install --user tensorboardX 
  - python examples/verify_network_cifar.py --model large --batch_size 1  
